import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, Building2, ChefHat, Check, Factory, HeartHandshake, Leaf, Play, Quote, Soup, Sprout, Star, Truck, UsersRound, ShieldCheck } from "lucide-react";
import farm from "@/assets/farm.jpg";
import flatlay from "@/assets/flatlay.jpg";
import hero from "@/assets/hero-onion.jpg";
import carrot from "@/assets/p-carrot.jpg";
import onion from "@/assets/p-onion.jpg";
import spinach from "@/assets/p-spinach.jpg";
import turmeric from "@/assets/p-turmeric.jpg";
import { ProductCard } from "@/components/site/ProductCard";
import { Counter, Reveal, SectionHeading } from "@/components/site/motion-primitives";
import { BLOG_POSTS, CATEGORIES, PRODUCTS, RECIPES, COMPANY_INFO } from "@/lib/products";

const categories = [
  { ...CATEGORIES[0], image: carrot },
  { ...CATEGORIES[1], image: turmeric },
  { ...CATEGORIES[2], image: spinach },
  { ...CATEGORIES[3], image: onion },
];

export default function HomePage() {
  const bestSellers = PRODUCTS.filter((product) => product.bestSeller).slice(0, 4);
  return (
    <main>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Organization", name: COMPANY_INFO.name, url: "https://utkarshorganic.com", description: "Organic dehydrated food powders for home and professional kitchens." }) }} />

      <section className="relative isolate min-h-[720px] overflow-hidden bg-forest pt-16 text-forest-foreground lg:min-h-[760px] lg:pt-20">
        <img src={hero} alt="Organic onion powder with fresh onions" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-45" />
        <div className="absolute inset-0 -z-10 bg-gradient-to-r from-forest via-forest/90 to-forest/40" />
        <div className="container-x grid min-h-[656px] items-center gap-10 py-16 lg:grid-cols-[1.15fr_0.85fr] lg:py-24">
          <Reveal y={32} className="max-w-2xl">
            <p className="inline-flex items-center gap-2 rounded-full border border-forest-foreground/25 bg-forest-foreground/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.16em]">
              <Leaf className="h-3.5 w-3.5 text-accent" /> {COMPANY_INFO.marathiHeader}
            </p>
            <h1 className="mt-7 font-display text-5xl font-extrabold leading-[1.04] tracking-tight sm:text-6xl lg:text-7xl">Real ingredients. <span className="text-accent">Ready</span> when you are.</h1>
            <p className="mt-6 max-w-xl text-base leading-relaxed text-forest-foreground/82 sm:text-lg">
              {COMPANY_INFO.marathiDescription}
            </p>
            <div className="mt-9 flex flex-wrap gap-3"><Link to="/shop" className="inline-flex items-center gap-2 rounded-full bg-accent px-6 py-3.5 text-sm font-bold text-accent-foreground transition hover:scale-[1.02]">Shop the collection <ArrowRight className="h-4 w-4" /></Link><Link to="/why-organic" className="inline-flex items-center gap-2 rounded-full border border-forest-foreground/35 px-6 py-3.5 text-sm font-bold transition hover:bg-forest-foreground/10">Why organic <Play className="h-3.5 w-3.5 fill-current" /></Link></div>
            <div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-forest-foreground/80"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-accent" /> 100% natural</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-accent" /> No preservatives</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-accent" /> FSSAI Reg. {COMPANY_INFO.fssaiRegNo}</span></div>
          </Reveal>
          <Reveal delay={0.15} className="hidden justify-self-end lg:block">
            <div className="relative w-80 rounded-[2rem] border border-forest-foreground/20 bg-forest-foreground/10 p-5 backdrop-blur-sm"><img src={onion} alt="Organic onion powder" className="h-80 w-full rounded-[1.5rem] object-cover" /><div className="absolute -bottom-6 -left-12 rounded-2xl bg-background p-4 text-foreground shadow-lift"><p className="text-xs font-bold uppercase tracking-widest text-accent">Kitchen essential</p><p className="mt-1 font-display text-lg font-bold">Organic Onion Powder</p><div className="mt-2 flex items-center gap-1 text-xs"><Star className="h-3.5 w-3.5 fill-saffron text-saffron" /> 4.9 / 5 from 214 cooks</div></div></div>
          </Reveal>
        </div>
      </section>

      <section className="border-y border-border bg-cream py-4"><div className="container-x flex flex-wrap items-center justify-center gap-x-9 gap-y-3 text-xs font-bold uppercase tracking-[0.1em] text-primary sm:justify-between"><span className="flex items-center gap-2"><BadgeCheck className="h-4 w-4 text-accent" /> Certified organic ingredients</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-accent" /> GSTIN: {COMPANY_INFO.gstin}</span><span className="flex items-center gap-2"><HeartHandshake className="h-4 w-4 text-accent" /> Satara Farm Direct</span><span className="flex items-center gap-2"><Leaf className="h-4 w-4 text-accent" /> FSSAI Reg. {COMPANY_INFO.fssaiRegNo}</span></div></section>

      <section className="container-x py-20 lg:py-28"><SectionHeading eyebrow="Find your flavour" title="Naturally good, in every category" sub="Every pack starts with carefully sourced produce from our Wai (Satara) farms, then takes the shortest, cleanest path to your pantry." /><div className="mt-11 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category, index) => <Reveal key={category.id} delay={index * 0.06}><Link to={`/shop?category=${category.id}`} className="group relative block h-72 overflow-hidden rounded-3xl bg-forest"><img src={category.image} alt="" className="h-full w-full object-cover opacity-75 transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-forest via-forest/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 text-forest-foreground"><p className="font-display text-xl font-bold">{category.name}</p><p className="mt-2 text-sm text-forest-foreground/75">{category.blurb}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-accent">Explore <ArrowRight className="h-3.5 w-3.5" /></span></div></Link></Reveal>)}</div></section>

      <section className="bg-beige/45 py-20 lg:py-28"><div className="container-x"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading align="left" eyebrow="Loved in real kitchens" title="Our best sellers" sub="The pantry staples cooks keep coming back for." /><Link to="/shop" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-primary hover:text-accent">Shop all products <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-11 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{bestSellers.map((product, index) => <Reveal key={product.slug} delay={index * 0.06}><ProductCard product={product} /></Reveal>)}</div></div></section>

      <section className="container-x py-20 lg:py-28"><div className="grid items-center gap-10 overflow-hidden rounded-[2rem] bg-forest p-7 text-forest-foreground md:p-10 lg:grid-cols-2 lg:p-14"><Reveal><p className="eyebrow text-accent">The everyday hero</p><h2 className="mt-4 font-display text-4xl font-extrabold leading-tight sm:text-5xl">One spoonful. <br />A world of flavour.</h2><p className="mt-5 max-w-lg leading-relaxed text-forest-foreground/75">Our signature Organic Onion Powder brings deep, savoury flavour to gravies, marinades, snacks and more—without the peeling or the prep.</p><ul className="mt-7 grid gap-3 sm:grid-cols-2">{["100% dehydrated onion", "No preservatives", "Fine, free-flowing texture", "Made for daily cooking"].map((item) => <li key={item} className="flex items-center gap-2 text-sm font-semibold"><Check className="h-4 w-4 text-accent" /> {item}</li>)}</ul><Link to="/product/organic-onion-powder" className="mt-9 inline-flex items-center gap-2 rounded-full bg-accent px-6 py-3.5 text-sm font-bold text-accent-foreground">Meet our onion powder <ArrowRight className="h-4 w-4" /></Link></Reveal><Reveal delay={0.12}><img src={flatlay} alt="Organic vegetable powder ingredients flat lay" className="h-[400px] w-full rounded-3xl object-cover" /></Reveal></div></section>

      <section className="bg-gradient-cream py-20 lg:py-28"><div className="container-x"><SectionHeading eyebrow="Our promise" title="Good for your plate. Better by nature." /><div className="mt-12 grid gap-5 md:grid-cols-3">{[{ icon: Sprout, title: "Thoughtfully sourced", text: "We begin with produce grown with care at Lohare / Gangapuri farms in Wai, Satara." }, { icon: Factory, title: "Gently processed", text: "Low-temperature dehydration keeps colour, aroma and everyday ease intact." }, { icon: HeartHandshake, title: "Honestly packed", text: "No fillers, artificial colour or shortcuts—just a clear ingredient list." }].map(({ icon: Icon, title, text }, index) => <Reveal key={title} delay={index * 0.08}><div className="surface-card h-full p-7"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-secondary text-accent"><Icon className="h-6 w-6" /></div><h3 className="mt-6 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></div></Reveal>)}</div></div></section>

      <section className="container-x py-20 lg:py-28"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr]"><Reveal><img src={farm} alt="A farm where our ingredients begin" className="h-full min-h-96 w-full rounded-[2rem] object-cover" /></Reveal><div><SectionHeading align="left" eyebrow="From farm to your table" title="A shorter journey makes better food." sub="We keep every stage clear and considered, so you know what arrives in your kitchen." /><ol className="mt-9 space-y-6">{[["01", "Grown with care", "Partner farms nurture each crop with mindful, responsible practices."], ["02", "Picked at its peak", "Only mature, flavourful produce makes it to the next stage."], ["03", "Gently dehydrated", "Controlled drying preserves the ingredients' honest character."], ["04", "Freshly packed", "Batch-checked and sealed to protect every spoonful."]].map(([number, title, text]) => <li key={number} className="flex gap-5"><span className="font-display text-2xl font-extrabold text-accent">{number}</span><div><h3 className="font-display font-bold">{title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{text}</p></div></li>)}</ol></div></div></section>

      <section className="bg-forest py-20 text-forest-foreground lg:py-24"><div className="container-x grid gap-10 lg:grid-cols-2"><Reveal><p className="eyebrow text-accent">Made for modern kitchens</p><h2 className="mt-4 max-w-lg font-display text-4xl font-extrabold sm:text-5xl">More flavour. Less waste. Zero fuss.</h2><p className="mt-5 max-w-xl leading-relaxed text-forest-foreground/75">Keep wholesome, versatile ingredients at hand—from a quick weekday tadka to a restaurant service that cannot slow down.</p></Reveal><div className="grid gap-4 sm:grid-cols-2">{[{ icon: Soup, text: "Saves prep time" }, { icon: Leaf, text: "Longer shelf life" }, { icon: ChefHat, text: "Consistent flavour" }, { icon: Truck, text: "Easy to store" }].map(({ icon: Icon, text }) => <div key={text} className="rounded-2xl border border-forest-foreground/15 bg-forest-foreground/5 p-5"><Icon className="h-5 w-5 text-accent" /><p className="mt-4 font-display font-bold">{text}</p></div>)}</div></div></section>

      <section className="container-x py-20 lg:py-28"><div className="overflow-hidden rounded-[2rem] bg-secondary px-7 py-12 md:px-12 lg:flex lg:items-center lg:justify-between lg:gap-12"><div className="max-w-2xl"><p className="eyebrow">For businesses that care</p><h2 className="mt-4 font-display text-4xl font-extrabold">Steady supply for serious food businesses.</h2><p className="mt-4 leading-relaxed text-muted-foreground">From cafés and cloud kitchens to manufacturers and exporters, our bulk packs bring consistent quality, custom formats and a human partnership.</p></div><Link to="/bulk-orders" className="mt-7 inline-flex shrink-0 items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-primary-foreground lg:mt-0">Talk bulk orders <ArrowRight className="h-4 w-4" /></Link></div></section>

      <section className="border-y border-border bg-cream py-14"><div className="container-x grid gap-8 text-center sm:grid-cols-2 lg:grid-cols-4">{[["10", "+", "clean ingredients"], ["4.8", "/5", "average customer rating"], ["12", "k+", "happy kitchen moments"], ["24", "hr", "dispatch support"]].map(([to, suffix, label]) => <div key={label}><p className="font-display text-4xl font-extrabold text-primary"><Counter to={Number(to)} suffix={suffix ?? ""} /></p><p className="mt-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">{label}</p></div>)}</div></section>

      <section className="container-x py-20 lg:py-28"><SectionHeading eyebrow="From our community" title="Kind words from well-fed kitchens" /><div className="mt-11 grid gap-5 lg:grid-cols-3">{[["I make gravies for 120 guests at a time. The onion powder is consistently fragrant, which makes a real difference to my prep.", "Chef Rohan Mehta", "Nashik"], ["The beetroot and spinach powders have become the easiest way to add colour to our weekend breakfast experiments.", "Ayesha Kulkarni", "Pune"], ["I appreciate being able to read exactly what is in every pack. The garlic powder is a permanent pantry item now.", "Nisha Shah", "Mumbai"]].map(([quote, name, place], index) => <Reveal key={name} delay={index * 0.08}><figure className="surface-card h-full p-7"><Quote className="h-7 w-7 text-accent" /><blockquote className="mt-5 text-sm leading-relaxed text-muted-foreground">“{quote}”</blockquote><figcaption className="mt-6"><p className="font-display font-bold">{name}</p><p className="text-xs text-muted-foreground">{place}</p></figcaption></figure></Reveal>)}</div></section>

      <section className="bg-beige/45 py-20 lg:py-28"><div className="container-x"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading align="left" eyebrow="Simple ideas" title="Make something nourishing" sub="Easy recipes with little shortcuts and plenty of flavour." /><Link to="/recipes" className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-primary hover:text-accent">See all recipes <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-11 grid gap-5 md:grid-cols-3">{RECIPES.slice(0, 3).map((recipe, index) => <Reveal key={recipe.slug} delay={index * 0.08}><Link to="/recipes" className="group surface-card block overflow-hidden"><img src={[flatlay, carrot, turmeric][index]} alt="" className="h-52 w-full object-cover transition duration-500 group-hover:scale-105" /><div className="p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">{recipe.time} &middot; {recipe.level}</p><h3 className="mt-2 font-display text-xl font-bold">{recipe.title}</h3><p className="mt-3 text-sm text-muted-foreground">Made with {recipe.uses.join(" and ")}</p></div></Link></Reveal>)}</div></div></section>

      <section className="container-x py-20 lg:py-28"><SectionHeading eyebrow="Field notes" title="A little more to savour" /><div className="mt-11 grid gap-5 md:grid-cols-3">{BLOG_POSTS.slice(0, 3).map((post, index) => <Reveal key={post.slug} delay={index * 0.08}><Link to={`/blog/${post.slug}`} className="group block h-full rounded-3xl border border-border bg-background p-6 transition hover:-translate-y-1 hover:shadow-lift"><p className="text-xs font-bold uppercase tracking-widest text-accent">Journal &middot; {post.read}</p><h3 className="mt-4 font-display text-xl font-bold leading-snug">{post.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-relaxed text-muted-foreground">{post.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">Read story <ArrowRight className="h-4 w-4" /></span></Link></Reveal>)}</div></section>

      <section className="overflow-hidden bg-forest py-16 text-forest-foreground"><div className="container-x flex flex-col items-center justify-between gap-8 text-center md:flex-row md:text-left"><div><p className="eyebrow text-accent">Follow along</p><h2 className="mt-3 font-display text-3xl font-extrabold">Good food starts with good choices.</h2></div><a href="https://instagram.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-forest-foreground/30 px-6 py-3 text-sm font-bold hover:bg-forest-foreground/10">@utkarshorganic <ArrowRight className="h-4 w-4" /></a></div><div className="mt-10 flex w-[160%] -translate-x-[18%] gap-4">{[farm, flatlay, onion, spinach, carrot, turmeric].map((image, index) => <img key={index} src={image} alt="A glimpse of Utkarsh Organic" className="h-40 min-w-48 rounded-2xl object-cover" />)}</div></section>

      <section className="container-x py-20 lg:py-24"><div className="rounded-[2rem] bg-secondary px-7 py-12 text-center md:px-12"><Leaf className="mx-auto h-8 w-8 text-accent" /><h2 className="mt-4 font-display text-3xl font-extrabold sm:text-4xl">A better pantry starts here.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-muted-foreground">Get simple recipe ideas, new product news and a gentle nudge to cook something good.</p><form className="mx-auto mt-7 flex max-w-md flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); (event.currentTarget.elements.namedItem("email") as HTMLInputElement).value = ""; }}><input name="email" required type="email" placeholder="Your email address" className="h-12 flex-1 rounded-full border border-border bg-background px-5 text-sm outline-none ring-ring focus:ring-2" /><button className="h-12 rounded-full bg-primary px-6 text-sm font-bold text-primary-foreground">Join the good list</button></form><p className="mt-3 text-xs text-muted-foreground">No noise. Just useful things for your kitchen.</p></div></section>
    </main>
  );
}
